# Generated by Django 3.1.4 on 2021-01-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookieManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingindex',
            old_name='CategaryDemandShare',
            new_name='CategoryDemandShare',
        ),
    ]
